CREATE TABLE IF NOT EXISTS `reading_sessions` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `read_pages` INT NOT NULL,
  `date` DATE NOT NULL,
  `book_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON DELETE CASCADE
);